"use client";

import { useState } from "react";
import PageHero from "@/components/PageHero";
import { CheckCircle2, Upload } from "lucide-react";

export default function RegisterPage(){
  const [done,setDone]=useState(false);
  if(done) return <><PageHero eyebrow="Registration" title="Terima kasih sudah mendaftar!" description="Data contoh berhasil diterima di sisi frontend. Hubungkan form ini ke API/database untuk penggunaan production."/><section className="py-24"><div className="mx-auto max-w-xl px-5 text-center"><CheckCircle2 className="mx-auto h-20 w-20 text-umado-blue"/><h2 className="mt-6 text-3xl font-black text-umado-navy">Welcome to the next step.</h2><button onClick={()=>setDone(false)} className="mt-7 rounded-full bg-umado-navy px-6 py-3 font-bold text-white">Isi Form Lagi</button></div></section></>;
  return <><PageHero eyebrow="Join Umado • 入会" title="Mulai perjalanan kreatifmu bersama Umado." description="Isi formulir berikut. Data di halaman demo ini belum dikirim ke server sampai Anda menghubungkannya dengan backend/API."/><section className="bg-slate-50 py-20"><div className="mx-auto max-w-3xl px-5"><form onSubmit={e=>{e.preventDefault();setDone(true)}} className="rounded-[32px] bg-white p-6 shadow-soft md:p-10"><div className="grid gap-5 md:grid-cols-2"><Field label="Nama Lengkap"><input required className="input" placeholder="Nama kamu"/></Field><Field label="Email"><input required type="email" className="input" placeholder="nama@email.com"/></Field><Field label="No. HP / WhatsApp"><input required className="input" placeholder="08xxxxxxxxxx"/></Field><Field label="Divisi yang diminati"><select required className="input"><option value="">Pilih divisi</option><option>Kasei — Song Cover & Dubbing</option><option>Manga</option><option>Dance Cover</option></select></Field></div><Field label="Motivasi Bergabung"><textarea required rows={5} className="input mt-0" placeholder="Ceritakan alasan kamu ingin bergabung dengan Umado..."/></Field><Field label="Portfolio / Dokumen (opsional)"><label className="flex cursor-pointer items-center justify-center gap-3 rounded-2xl border-2 border-dashed border-slate-200 p-7 text-slate-500 hover:border-umado-blue hover:bg-sky-50"><Upload/><span>Upload file portfolio / dokumen</span><input type="file" className="hidden"/></label></Field><label className="mt-5 flex items-start gap-3 text-sm text-slate-600"><input required type="checkbox" className="mt-1"/>Saya menyetujui data digunakan untuk proses pendaftaran anggota Umado.</label><button className="mt-7 w-full rounded-2xl bg-umado-blue px-6 py-4 font-black text-white shadow-lg shadow-sky-200 hover:bg-sky-600">Kirim Pendaftaran</button></form></div></section><style jsx global>{`.input{width:100%;border:1px solid #dbe3eb;border-radius:16px;padding:13px 14px;outline:none;background:white}.input:focus{border-color:#159dda;box-shadow:0 0 0 3px rgba(21,157,218,.12)}`}</style></>;
}
function Field({label,children}:{label:string;children:React.ReactNode}){return <label className="mb-5 block"><span className="mb-2 block text-sm font-bold text-umado-navy">{label}</span>{children}</label>}
